/**
 * 事件的EventNum
 */

export namespace EventKeys {

  /**
   * 项目通用
   */
  export class AppEventKeys {
    //展示loading的事件处理EventID
    static readonly LOADING_DIALOG_EVENT = "loading_dialog_event"
  }

  /**
   * 首页事件
   */
  export class HomeEventKeys {
  }

  /**
   * 发现模块事件
   */
  export class DiscoverEventKeys {
  }

  /**
   * 排行榜模块事件
   */
  export class RankEventKeys {
  }


  /**
   * 我的模块事件
   */
  export class MineEventKeys {
  }


}

